spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-demo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081


